package com.fitnesstracker;

public class FitnessHtmlBuilder {
    public static String buildPage() {
        StringBuilder html = new StringBuilder();
        append(html, "<!DOCTYPE html>");
        append(html, "<html lang=\"en\">");
        append(html, "<head>");
        append(html, "<meta charset=\"UTF-8\">");
        append(html, "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">");
        append(html, "<title>Fitness Tracker</title>");
        append(html, "<style>");
        append(html, "body{margin:0;font-family:Inter,system-ui,sans-serif;background:#0d2355;color:#fff;min-height:100vh;display:flex;align-items:center;justify-content:center;}");
        append(html, ".app-shell{width:min(1000px,95vw);background:#112f69;border:1px solid rgba(255,255,255,.12);border-radius:28px;overflow:hidden;box-shadow:0 24px 80px rgba(0,0,0,.35);}");
        append(html, ".hero{padding:32px 28px;display:grid;gap:24px;}");
        append(html, ".title{font-size:clamp(2rem,4vw,3.2rem);font-weight:800;line-height:1.05;}");
        append(html, ".subtitle{color:#c9d7ff;max-width:44rem;font-size:1rem;line-height:1.8;margin-top:-8px;}");
        append(html, ".page-wrap{position:relative;overflow:hidden;height:650px;}");
        append(html, ".pages{display:flex;transition:transform .7s ease;min-height:100%;}");
        append(html, ".panel{flex:0 0 100%;padding:32px 28px;display:grid;gap:18px;box-sizing:border-box;}");
        append(html, ".bubble{background:rgba(255,255,255,.08);border:1px solid rgba(255,255,255,.14);backdrop-filter:blur(16px);border-radius:24px;padding:22px;}");
        append(html, ".bubble label{display:block;font-size:.95rem;color:#d7e1ff;margin-bottom:12px;}");
        append(html, ".bubble input,.bubble select{width:100%;border:none;border-radius:16px;padding:14px 16px;background:rgba(255,255,255,.08);color:#fff;font-size:1rem;outline:none;box-shadow:inset 0 0 0 1px rgba(255,255,255,.08);}");
        append(html, ".bubble input::placeholder{color:rgba(255,255,255,.65);}");
        append(html, ".row{display:grid;gap:16px;}");
        append(html, ".row-cols-2{grid-template-columns:1fr 1fr;}");
        append(html, ".button{background:#3b7cff;color:#fff;border:none;border-radius:18px;padding:16px 24px;font-size:1rem;font-weight:700;cursor:pointer;transition:transform .2s ease,background .2s ease;}");
        append(html, ".button:hover{transform:translateY(-1px);background:#5487ff;}");
        append(html, ".button.secondary{background:rgba(255,255,255,.08);color:#eef2ff;}");
        append(html, ".note{font-size:.95rem;color:#b8c9ff;}");
        append(html, ".modal-backdrop{position:fixed;inset:0;background:rgba(3,13,54,.82);display:none;align-items:center;justify-content:center;padding:24px;z-index:50;}");
        append(html, ".modal{background:#112d61;border:1px solid rgba(255,255,255,.14);border-radius:28px;max-width:560px;width:100%;padding:28px;}");
        append(html, ".modal h2{margin-top:0;color:#fff;}");
        append(html, ".modal p{line-height:1.8;color:#d5e0ff;}");
        append(html, ".close-btn{margin-top:24px;background:#183c8d;padding:14px 18px;border-radius:16px;display:inline-block;}");
        append(html, ".date-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;}");
        append(html, "@media(max-width:720px){.page-wrap{height:auto;}.row-cols-2{grid-template-columns:1fr;}.date-grid{grid-template-columns:1fr;}} ");
        append(html, "</style>");
        append(html, "</head>");
        append(html, "<body>");
        append(html, "<div class=\"app-shell\">");
        append(html, "  <div class=\"hero\">");
        append(html, "    <div><div class=\"title\">Fitness Tracker</div><div class=\"subtitle\">Enter your height, weight, age, and your target plan. Get a healthy suggestion sheet and timeline estimate.</div></div>");
        append(html, "  </div>");
        append(html, "  <div class=\"page-wrap\">");
        append(html, "    <div class=\"pages\" id=\"pages\">");
        append(html, "      <section class=\"panel\" id=\"page1\">");
        append(html, "        <div class=\"bubble\"><label for=\"height\">Height (inches)</label><input id=\"height\" type=\"number\" min=36 max=96 placeholder=\"Example: 68\"></div>");
        append(html, "        <div class=\"bubble\"><label for=\"weight\">Current Weight (lbs)</label><input id=\"weight\" type=\"number\" min=40 step=0.1 placeholder=\"Example: 155\"></div>");
        append(html, "        <div class=\"bubble\"><label for=\"age\">Age</label><input id=\"age\" type=\"number\" min=10 max=120 placeholder=\"Example: 28\"></div>");
        append(html, "        <div class=\"bubble note\">All text is white and readable on the dark blue background. Tap Enter to continue.</div>");
        append(html, "        <button class=\"button\" id=\"nextBtn\">Enter</button>");
        append(html, "      </section>");
        append(html, "      <section class=\"panel\" id=\"page2\">");
        append(html, "        <div class=\"bubble\"><label for=\"goal\">Fitness Goal</label><select id=\"goal\"><option>Gaining Weight</option><option>Gaining Muscle</option><option>Losing Weight</option><option>Losing Fat</option><option>Proper Diet</option><option>Any General Advice</option></select></div>");
        append(html, "        <div class=\"bubble\"><label for=\"diet\">Diet Type</label><select id=\"diet\"><option>Non-vegetarian</option><option>Vegetarian</option><option>Vegan</option></select></div>");
        append(html, "        <div class=\"bubble\"><label>Target Date</label><div class=\"date-grid\"><input id=\"month\" type=\"number\" min=4 max=12 placeholder=\"MM\"><input id=\"day\" type=\"number\" min=1 max=31 placeholder=\"DD\"><input id=\"year\" type=\"number\" min=2026 max=2100 placeholder=\"YYYY\"></div></div>");
        append(html, "        <div class=\"bubble row row-cols-2\"><div><label for=\"targetWeight\">Target Weight</label><input id=\"targetWeight\" type=\"number\" min=30 step=0.1 placeholder=\"Example: 170\"></div><div><label for=\"unit\">Unit</label><select id=\"unit\"><option value=\"lbs\">Pounds (lbs)</option><option value=\"kg\">Kilograms (kg)</option></select></div></div>");
        append(html, "        <div class=\"bubble note\">Toggle unit to enter weight in pounds or kilograms. Then tap Enter for your plan.</div>");
        append(html, "        <button class=\"button\" id=\"submitBtn\">Enter</button>");
        append(html, "      </section>");
        append(html, "    </div>");
        append(html, "  </div>");
        append(html, "</div>");
        append(html, "<div class=\"modal-backdrop\" id=\"modalBackdrop\">");
        append(html, "  <div class=\"modal\"><h2>Your Fitness Plan</h2><div id=\"modalContent\"></div><a class=\"close-btn button secondary\" id=\"closeModal\">Close</a></div>");
        append(html, "</div>");
        append(html, "<script>");
        append(html, "const pages = document.getElementById('pages');");
        append(html, "const nextBtn = document.getElementById('nextBtn');");
        append(html, "const submitBtn = document.getElementById('submitBtn');");
        append(html, "const modalBackdrop = document.getElementById('modalBackdrop');");
        append(html, "const closeModal = document.getElementById('closeModal');");
        append(html, "const modalContent = document.getElementById('modalContent');");
        append(html, "const minTarget = new Date(2026, 3, 1);");
        append(html, "nextBtn.addEventListener('click', () => { const height = Number(document.getElementById('height').value); const weight = Number(document.getElementById('weight').value); const age = Number(document.getElementById('age').value); if (!height || !weight || !age) { alert('Please enter height, weight, and age before continuing.'); return; } pages.style.transform = 'translateX(-100%)'; });");
        append(html, "closeModal.addEventListener('click', () => { modalBackdrop.style.display = 'none'; });");
        append(html, "modalBackdrop.addEventListener('click', event => { if (event.target === modalBackdrop) { modalBackdrop.style.display = 'none'; } });");
        append(html, "submitBtn.addEventListener('click', () => { const goal = document.getElementById('goal').value; const diet = document.getElementById('diet').value; const month = Number(document.getElementById('month').value); const day = Number(document.getElementById('day').value); const year = Number(document.getElementById('year').value); const targetWeight = Number(document.getElementById('targetWeight').value); const unit = document.getElementById('unit').value; const currentWeight = Number(document.getElementById('weight').value); const height = Number(document.getElementById('height').value); const age = Number(document.getElementById('age').value); if (!month || !day || !year || !targetWeight) { alert('Please complete target date and weight.'); return; } const targetDate = new Date(year, month - 1, day); if (targetDate <= minTarget) { alert('Choose a date after 4/1/2026.'); return; } if (targetWeight <= 0) { alert('Enter a healthy target weight.'); return; } const weightTargetLbs = unit === 'kg' ? targetWeight * 2.20462 : targetWeight; modalContent.innerHTML = buildAdvice({ goal, diet, currentWeight, height, age, targetDate, weightTargetLbs }); modalBackdrop.style.display = 'flex'; });");
        append(html, "function buildAdvice(data) {");
        append(html, "  const today = new Date();");
        append(html, "  const days = Math.max(1, Math.round((data.targetDate - today) / 86400000));");
        append(html, "  const diff = Math.round((data.weightTargetLbs - data.currentWeight) * 10) / 10;");
        append(html, "  const absDiff = Math.abs(diff);");
        append(html, "  const weeks = days / 7;");
        append(html, "  const pace = absDiff / Math.max(1, weeks);");
        append(html, "  const dailyMaint = estimateMaintenance(data.currentWeight, data.height, data.age);");
        append(html, "  let calorieMessage = '';");
        append(html, "  let advice = '';");
        append(html, "  if (data.goal === 'Gaining Weight' || data.goal === 'Gaining Muscle') {");
        append(html, "    const needed = diff > 0 ? diff : absDiff;");
        append(html, "    const totalDelta = needed * 3500;");
        append(html, "    const dailyDelta = Math.round(totalDelta / days);");
        append(html, "    calorieMessage = `Based on an estimated maintenance of ${dailyMaint} calories, aim for about ${dailyMaint + dailyDelta} calories per day to reach ${toFixed(data.weightTargetLbs, 1)} lbs by ${formatDate(data.targetDate)}.`;");
        append(html, "  } else if (data.goal === 'Losing Weight' || data.goal === 'Losing Fat') {");
        append(html, "    const needed = diff < 0 ? absDiff : diff;");
        append(html, "    const totalDelta = needed * 3500;");
        append(html, "    const dailyDelta = Math.round(totalDelta / days);");
        append(html, "    calorieMessage = `Based on an estimated maintenance of ${dailyMaint} calories, a daily target of ${dailyMaint - dailyDelta} calories can help you reach ${toFixed(data.weightTargetLbs, 1)} lbs by ${formatDate(data.targetDate)}.`;");
        append(html, "  } else {");
        append(html, "    calorieMessage = `Your estimated maintenance calories are about ${dailyMaint} per day based on your current height, weight, and age. Use that as your baseline.`;");
        append(html, "  }");
        append(html, "  if (days < 14 && absDiff > 4) {");
        append(html, "    advice += '<p><strong>Warning:</strong> Your timeline is aggressive. Aim for 1–2 lbs per week instead.</p>';" );
        append(html, "  }");
        append(html, "  if (data.goal === 'Gaining Weight') { advice += foodAdvice(data.diet, 'gain'); }");
        append(html, "  else if (data.goal === 'Gaining Muscle') { advice += '<p>Do strength training 3–5 times per week. Eat plenty of protein and maintain a moderate calorie surplus.</p>' + dietProteinNote(data.diet); }");
        append(html, "  else if (data.goal === 'Losing Weight') { advice += foodAdvice(data.diet, 'lose'); }");
        append(html, "  else if (data.goal === 'Losing Fat') { advice += '<p>Combine strength training with cardio, reduce sugar and processed foods, and stay in a gentle calorie deficit.</p>' + dietProteinNote(data.diet); }");
        append(html, "  else if (data.goal === 'Proper Diet') { advice += '<p>Track calories, protein, carbs, and fat. A balanced plan includes protein, vegetables, whole grains, and healthy fats.</p><p>Calorie surplus supports growth; calorie deficit supports fat loss.</p>'; }");
        append(html, "  else { advice += '<p>General advice: move consistently, eat whole foods, sleep well, hydrate, and manage stress.</p>'; }");
        append(html, "  if ((data.goal === 'Gaining Weight' || data.goal === 'Losing Weight' || data.goal === 'Losing Fat') && pace > 2.5) { advice += '<p><strong>Note:</strong> Your goal may be unhealthy. A safer pace is 1–2 lbs per week.</p>'; }");
        append(html, "  return `<div>${calorieMessage}</div>${advice}`;");
        append(html, "}");
        append(html, "function estimateMaintenance(weight, height, age) { const heightCm = height * 2.54; const weightKg = weight / 2.20462; const bmr = 10 * weightKg + 6.25 * heightCm - 5 * age + 5; return Math.round(bmr * 1.4); }");
        append(html, "function foodAdvice(diet, type) { if (type === 'gain') { return diet === 'Non-vegetarian' ? '<p>Choose nutrient-rich meals with lean meats, eggs, dairy, nuts, avocado, and whole grains.</p>' : '<p>Choose lentils, beans, tofu, nuts, seeds, whole grains, and healthy fats like avocado.</p>'; } return diet === 'Non-vegetarian' ? '<p>Choose lean meats, vegetables, whole grains, and fiber. Reduce sugary snacks and refined carbs.</p>' : '<p>Choose legumes, whole grains, vegetables, nuts, and seeds. Cut processed foods and prioritize plant protein.</p>'; }");
        append(html, "function dietProteinNote(diet) { if (diet === 'Vegan') { return '<p>Use legumes, tofu, tempeh, and seitan to reach your protein goals.</p>'; } if (diet === 'Vegetarian') { return '<p>Use dairy, eggs, and legumes for steady protein intake.</p>'; } return '<p>Use chicken, fish, eggs, and lean beef for efficient protein and amino acids.</p>'; }");
        append(html, "function toFixed(value, places) { return Number(value.toFixed(places)); }");
        append(html, "function formatDate(date) { return `${date.getMonth() + 1}/${date.getDate()}/${date.getFullYear()}`; }");
        append(html, "</script>");
        append(html, "</body>");
        append(html, "</html>");
        return html.toString();
    }

    private static void append(StringBuilder html, String line) {
        html.append(line).append('\n');
    }
}
